import {
  UNIFIED_WORKFLOW_STAGES,
} from "../../shared/unified-workflow-stages.mjs";

export const UNIFIED_WORKFLOW_LAYOUT_STORAGE_KEY_PREFIX = "taskboard.unified-board.layout.v1:";
export const UNIFIED_WORKFLOW_ZIP_EXPANSION_KEY_PREFIX = "zip:";
export const MAX_UNIFIED_WORKFLOW_ZIP_EXPANSION_KEY_LENGTH = 512;

const COLUMN_WIDTH_PRESETS = Object.freeze({
  narrow: 280,
  standard: 340,
  wide: 420,
});
const COLUMN_WIDTH_PRESET_IDS = new Set(Object.keys(COLUMN_WIDTH_PRESETS));
const CARD_DENSITIES = new Set(["compact", "comfortable"]);
const STAGE_IDS = new Set(UNIFIED_WORKFLOW_STAGES);
const CONTROL_CHARACTER_PATTERN = /[\u0000-\u001f\u007f-\u009f]/u;

/** @typedef {"narrow" | "standard" | "wide"} UnifiedColumnWidthPreset */
/** @typedef {"compact" | "comfortable"} UnifiedCardDensity */
/**
 * @typedef {Object} UnifiedWorkflowLayoutState
 * @property {UnifiedColumnWidthPreset} columnWidthPreset
 * @property {UnifiedCardDensity} cardDensity
 * @property {number} boardScrollLeft
 * @property {Record<string, number>} columnScrollTop
 * @property {Record<string, boolean>} zipExpansion
 */

function isRecord(value) {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function safeScopePart(value) {
  // IDs are generated by Taskboard, but encoding keeps user-created project IDs
  // from colliding when they contain separators or path-like characters.
  const text = typeof value === "string" ? value : String(value ?? "");
  return encodeURIComponent(text);
}

function allowedStageIds(value) {
  const source = value === undefined || value === null
    ? UNIFIED_WORKFLOW_STAGES
    : Array.isArray(value) ? value : UNIFIED_WORKFLOW_STAGES;
  const seen = new Set();
  const result = [];
  for (const stageId of source) {
    if (typeof stageId !== "string" || !STAGE_IDS.has(stageId) || seen.has(stageId)) continue;
    seen.add(stageId);
    result.push(stageId);
  }
  return result;
}

function nonNegativeFiniteNumber(value) {
  return typeof value === "number" && Number.isFinite(value) && value >= 0
    ? Math.max(0, value)
    : 0;
}

function validZipExpansionKey(key) {
  return typeof key === "string"
    && key.startsWith(UNIFIED_WORKFLOW_ZIP_EXPANSION_KEY_PREFIX)
    && key.length <= MAX_UNIFIED_WORKFLOW_ZIP_EXPANSION_KEY_LENGTH
    && !CONTROL_CHARACTER_PATTERN.test(key);
}

function browserLocalStorage() {
  try {
    const storage = globalThis.localStorage;
    if (!storage
      || typeof storage.getItem !== "function"
      || typeof storage.setItem !== "function"
      || typeof storage.removeItem !== "function") {
      return null;
    }
    return storage;
  } catch {
    return null;
  }
}

/**
 * Build the browser-only storage key for one project and one workflow view.
 * @param {string} projectId
 * @param {string} viewId
 * @returns {string}
 */
export function unifiedWorkflowLayoutStorageKey(projectId, viewId) {
  return `${UNIFIED_WORKFLOW_LAYOUT_STORAGE_KEY_PREFIX}${safeScopePart(projectId)}:${safeScopePart(viewId)}`;
}

/**
 * Build the stable key used for one task/artifact ZIP disclosure.
 * @param {string} taskId
 * @param {string} artifactIdentity
 * @returns {string}
 */
export function unifiedWorkflowZipExpansionKey(taskId, artifactIdentity) {
  const task = typeof taskId === "string" ? taskId : String(taskId ?? "");
  const artifact = typeof artifactIdentity === "string"
    ? artifactIdentity
    : String(artifactIdentity ?? "");
  if (!task || !artifact || CONTROL_CHARACTER_PATTERN.test(task) || CONTROL_CHARACTER_PATTERN.test(artifact)) {
    throw new TypeError("taskId and artifactIdentity must be non-empty safe strings");
  }
  const key = `${UNIFIED_WORKFLOW_ZIP_EXPANSION_KEY_PREFIX}${encodeURIComponent(task)}:${encodeURIComponent(artifact)}`;
  if (key.length > MAX_UNIFIED_WORKFLOW_ZIP_EXPANSION_KEY_LENGTH) {
    throw new TypeError("ZIP expansion identity is too long");
  }
  return key;
}

/**
 * Normalize untrusted layout data without mutating the supplied object.
 * @param {unknown} value
 * @param {readonly string[]} [activeStageIds]
 * @returns {UnifiedWorkflowLayoutState}
 */
export function normalizeUnifiedWorkflowLayout(value, activeStageIds = UNIFIED_WORKFLOW_STAGES) {
  const source = isRecord(value) ? value : {};
  const stages = allowedStageIds(activeStageIds);
  const columnScrollTop = {};
  if (isRecord(source.columnScrollTop)) {
    for (const stageId of stages) {
      if (Object.prototype.hasOwnProperty.call(source.columnScrollTop, stageId)) {
        columnScrollTop[stageId] = nonNegativeFiniteNumber(source.columnScrollTop[stageId]);
      }
    }
  }

  const zipExpansion = {};
  if (isRecord(source.zipExpansion)) {
    for (const [key, expanded] of Object.entries(source.zipExpansion)) {
      if (validZipExpansionKey(key) && typeof expanded === "boolean") {
        zipExpansion[key] = expanded;
      }
    }
  }

  /** @type {UnifiedWorkflowLayoutState} */
  return {
    columnWidthPreset: COLUMN_WIDTH_PRESET_IDS.has(source.columnWidthPreset)
      ? source.columnWidthPreset
      : "standard",
    cardDensity: CARD_DENSITIES.has(source.cardDensity)
      ? source.cardDensity
      : "comfortable",
    boardScrollLeft: nonNegativeFiniteNumber(source.boardScrollLeft),
    columnScrollTop,
    zipExpansion,
  };
}

/**
 * Read and normalize one scoped layout preference from localStorage.
 * Storage access is deliberately best-effort because private browser contexts
 * can expose a throwing or unavailable localStorage implementation.
 * @param {string} projectId
 * @param {string} viewId
 * @param {readonly string[]} [activeStageIds]
 * @returns {UnifiedWorkflowLayoutState}
 */
export function readUnifiedWorkflowLayout(projectId, viewId, activeStageIds = UNIFIED_WORKFLOW_STAGES) {
  const storage = browserLocalStorage();
  if (!storage) return normalizeUnifiedWorkflowLayout(null, activeStageIds);
  try {
    const raw = storage.getItem(unifiedWorkflowLayoutStorageKey(projectId, viewId));
    return normalizeUnifiedWorkflowLayout(raw ? JSON.parse(raw) : null, activeStageIds);
  } catch {
    return normalizeUnifiedWorkflowLayout(null, activeStageIds);
  }
}

/**
 * Normalize and write one scoped layout preference.
 * @param {string} projectId
 * @param {string} viewId
 * @param {unknown} value
 * @param {readonly string[]} [activeStageIds]
 * @returns {UnifiedWorkflowLayoutState}
 */
export function writeUnifiedWorkflowLayout(projectId, viewId, value, activeStageIds = UNIFIED_WORKFLOW_STAGES) {
  const normalized = normalizeUnifiedWorkflowLayout(value, activeStageIds);
  const storage = browserLocalStorage();
  if (!storage) return normalized;
  try {
    storage.setItem(
      unifiedWorkflowLayoutStorageKey(projectId, viewId),
      JSON.stringify(normalized),
    );
  } catch {
    // A disabled/quota-limited browser storage must not break the board.
  }
  return normalized;
}

/**
 * Remove one scoped layout preference and return a fresh default state.
 * @param {string} projectId
 * @param {string} viewId
 * @param {readonly string[]} [activeStageIds]
 * @returns {UnifiedWorkflowLayoutState}
 */
export function resetUnifiedWorkflowLayout(projectId, viewId, activeStageIds = UNIFIED_WORKFLOW_STAGES) {
  const storage = browserLocalStorage();
  if (storage) {
    try {
      storage.removeItem(unifiedWorkflowLayoutStorageKey(projectId, viewId));
    } catch {
      // Reset remains a successful no-op when browser storage is unavailable.
    }
  }
  return normalizeUnifiedWorkflowLayout(null, activeStageIds);
}

/**
 * Remove all saved layouts belonging to one project without touching another
 * project's views or unrelated browser storage.
 * @param {string} projectId
 */
export function clearUnifiedWorkflowLayoutsForProject(projectId) {
  const storage = browserLocalStorage();
  if (!storage) return;

  let length;
  let keyAt;
  try {
    length = storage.length;
    keyAt = storage.key;
  } catch {
    return;
  }
  if (!Number.isInteger(length) || length < 0 || typeof keyAt !== "function") return;

  const prefix = `${UNIFIED_WORKFLOW_LAYOUT_STORAGE_KEY_PREFIX}${safeScopePart(projectId)}:`;
  const keys = [];
  try {
    for (let index = 0; index < length; index += 1) {
      const key = keyAt.call(storage, index);
      if (typeof key === "string" && key.startsWith(prefix)) keys.push(key);
    }
  } catch {
    return;
  }

  for (const key of keys) {
    try {
      storage.removeItem(key);
    } catch {
      // Browser storage may become unavailable between enumeration and removal.
    }
  }
}

/**
 * Resolve a stable pixel width for the column-width preset.
 * @param {UnifiedColumnWidthPreset} preset
 * @returns {number}
 */
export function columnWidthPx(preset) {
  return COLUMN_WIDTH_PRESETS[preset] ?? COLUMN_WIDTH_PRESETS.standard;
}
